# Gradle Properties
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod Properties
mod_version=1.6.5-CLEAN
maven_group=com.sxrth.obsidian
archives_base_name=ObsidianOptimization

# Dependencies
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3:v2
loader_version=0.16.0
fabric_version=0.102.0+1.21.1
